server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service             # Nombre identificador de la ruta
          uri: http://localhost:8081      # A dónde se redirige (el microservicio real)
          predicates:
            - Path=/products/**           # Qué rutas intercepta (todas las que empiezan con /products/)
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCB    # Nombre del circuito (debe coincidir con la config de resilience4j)
                fallbackUri: forward:/fallback-products   # Qué hacer si falla el servicio: redirigir internamente

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      productServiceCB:
        slidingWindowSize: 2
        minimumNumberOfCalls: 1
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

  timelimiter:
    instances:
      productServiceCB:
        timeoutDuration: 2s